-- defaults --
require("opts")
require("mappings")
require("plugins")

-- themes--
-- require('themes.onedark')
-- require('themes.neon')
-- require('themes.calvera')
-- require('themes.rosepine')
-- require('themes.tokyonight')
require("anik.colorizer-setup")
-- statusline
require("anik.statusline-setup")
-- require('anik.windline-setup')
require("anik.bufferline-setup")
require("anik.indent_blankline-setup")
require("anik.nvimcomment-setup")
require("anik.dashboard-setup")
require("anik.nvimtree-setup")
require("anik.floatterm-setup")
require("anik.gitsigns-setup")
-- lsp --
-- require('anik.lspconfig-setup')
require("anik.cmp-setup")
require("anik.lsp")
require("anik.lspsaga-setup")
require("anik.treesitter-setup")
require("anik.project")
require("anik.telescope-setup")
require("anik.whichkey-setup")
vim.cmd("colo darkplus")
